### ISSUE TITLE
"Warning: Can only update a mounted or mounting component." when navigating to another screen

### ISSUE THREAD

**Issue by toussa** [react-native-community/react-native-modal#111]
Hi,

I'm using some modals with a button "go back" that dispatch 2 actions:
- One to go to the previous screen.
- One that will clean the state, which is used as props. It's linked to the isVisible props of my modal.

The modal is displayed correctly, but, then, when I hit the goBack button, I arrive on the right screen (and a clean state) with the following yellow warning:
>  Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
> 
> Please check the code for the ReactNativeModal component.

I checked my code with the original Modal of react native, and it works well (no warning).
I'm using `react-native-cli: 2.0.1` and `react-native: 0.50.3`, with `"react-native-modal": "^4.1.1",` , targetting Android (emulators).

When I don't dispatch the clean action, it works without warning. I think this is related to that cleanup forcing a re-render while unmounting the screen's component. It seems related to this [stackoverflow question](https://stackoverflow.com/questions/34544314/setstate-can-only-update-a-mounted-or-mounting-component-this-usually-mea) (TL;DR: trying to do a setState or setInterval or whatever on something that has been unmounted.)

Here is my modal:
```
<Modal
        style={styles.Modal}
        isVisible={this.props.isVisible}
        transparent={true}
        backdropColor="rgba(0,0,0,0.5)"
        useNativeDriver={false} // because of "white flickering" when modal appear and disappear
        {...props}
      >
        <View padder style={styles.ModalContent}>
          {this.props.children}
        </View>
 </Modal>
```
and the goBack() method that's called when pressing a button: `goBack: () => {
      dispatch(NavigationActions.back());
      dispatch(UserActions.userClean());
    }`

**Comment by toussa** [comment]
Here is another link that may help: [reactjs blog: why isMounted is an antipattern](https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html).

**Comment by mmazzarolo** [comment]
Hi!  

I would probably need more info on what your two actions are actually doing, but from my understanding you're unmounting the screen where the modal is defined while setting the `isVisible` prop to `false`, am I right? 
  
This would probably produce the yellow warning because when you set the `isVisible` prop to `false` the modal will first and animate out and then set its own internal state.  
  
There are 3 ways you can fix the issue:
1. Ignore it, it shouldn't harm (worst choice though)
2. Just unmount the component without setting `isVisible` to `false`
3. Set `isVisible` to `false` and, after the animation completes, unmount the component (you can tell when the animation complete by using the `onModalHide` callback prop).

**Comment by mmazzarolo** [comment]
@toussa I'm closing the issue but feel free to post again here if you're still having troubles with the warning 👍

**Comment by toussa** [comment]
Hello @mmazzarolo, thanks for your response.

yes you're right, this is exactly what It's doing, unmounting the screen while setting visible to false.

You're right, these 3 ways fix the warning.
But it seems they are "just" workarounds and do not fix the underlying issue, which is probably related to animation as you said (or some kind of timer).
Some action that's not cleaned correctly when unmounting the component. I tried rapidly to look through the source code but without success.

**Comment by mmazzarolo** [comment]
> But it seems they are "just" workarounds and do not fix the underlying issue, which is probably related to animation as you said (or some kind of timer).  

The third option I listed is not a workaround, it is the correct way you should handle this situation in my opinion.  
If you're interested in the modal exit animation you should do it that way (animating a component "exit" can only be done by keeping track of its state internally), otherwise, you could simply do it by un-mounting it without setting its state (which is the React-way for doing this kind of stuff, but that doesn't allow you to animate this transition). 
Let me know if it sounds ok to you 👍

**Comment by toussa** [comment]
Well, the third option is logic, indeed. It can be seen this way. And that's what I gonna do for now. Thanks.

Relating to animation, I don't know much, but there is no warning at all when using the original React modal, with `animationType={'slide'}`. The modal slides out and the screen changes, as expected. That's why I thought there was some conditional verification missing somewhere.

**Comment by sauhardar** [comment]
I'm having issues unmounting the modal after the modal animation while using `onModalHide`. It seems that the callback isn't called even after the modal is hidden after the animation completes. Does anyone have any more experience with this?
