### ISSUE TITLE
swiper issue with modal

### ISSUE THREAD

**Issue by pherm** [react-native-community/react-native-modal#117]
Hi, I'm working with modals and page swiper (react-native-swiper). I added a different modal to each screen of Swiper Page (3 screens, for now) and it always returns a modal wrong for the printing page. I would like to print a correct modal for each screen which i call. Any suggestions?

**Comment by LouisJS** [comment]
Please provide an example of what you're trying to achieve. (on [snack.expo.io](https://snack.expo.io/))
By reading your post, we have no idea what you mean by 'wrong' so we won't be able to provide any suggestions.
Also, lower case the title of this issue.

**Comment by pherm** [comment]
[here](https://snack.expo.io/SyjcC0aPf)

**Comment by mmazzarolo** [comment]
Thanks @LouisJS for helping out

@pherm, since the issue seems a bit complex (it involves interactions with another external library) I won't be able to offer you a quick support, but I'll try to take a look at the example as soon as I have some free time.  

From a quick look though, it seems you have multiple modals controlled by the same variable (`isModalVisible`), which is not the right pattern to follow: you should instead save in the state the information of WHICH modal you want to show (e.g. by identifying each modal with a string constant).  
An even better way to handle this situation would be using a single modal (isolated in another component) and changing its content by setting the props.

P.S.: Ciao, mi sa proprio che sei anche tu italiano :)

**Comment by pherm** [comment]
Oo, anyway thanks @LouisJS for helping out

si, @mmazzarolo, grazie dell'aiuto Matteo :) Non ho ancora capito come risolvere il problema, ad ogni pagina screen ho impostato un modale di descrizione ma quando passo ad un'altra pagina di screen mi ritorna la descrizione di un modale diverso da quello che dovrebbe ritornarmi per il medesimo prodotto. Consigli di impostare un singolo modale isolato dal resto? Se sì, come? Ogni suggerimento è ben accetto. Grazie

**Comment by mmazzarolo** [comment]
Il problema principale che vedo è che stai usando due modali che son controllate entrambe dalla stessa variabile (`isModalVisibile`). 
Dai un'occhiata a [questo esempio](https://github.com/react-native-community/react-native-modal/blob/master/example/src/app.js) che usa più modali, puoi prenderci spunto.

**Comment by pherm** [comment]
ciao @mmazzarolo il problema l'ho in parte risolto. Per ogni pagina di screen ritorna il corretto modale. Tuttavia quando richiamo il modale corretto per la relativa pagina (esempio: 2ndo modale della 2nda pagina di screen) l'app riporta sì il corretto modale ma fa anche un reset e mi riporta alla pagina di screen primaria (nel mio caso la pagine di screen 1). Il mio obiettivo è richiamare il corretto modale nella pagina di screen corretta senza che si generi un reset che riporti alla pagina di screen iniziale (ossia screen1).

**Comment by mmazzarolo** [comment]
ciao @pherm, mi dispiace non poterti aiutare troppo ma il problema di cui stai parlando non è collegato a react-native-modal (non è una issue)... ti consiglio di rivolgere la domanda su stackoverflow taggandola con "react-native"!
