### ISSUE TITLE
Modal remains open after refresh

### ISSUE THREAD

**Issue by udarts** [react-native-community/react-native-modal#150]
This issue persists in both the original modal of react-native and this version (testing on real iPhone 7+  device).

When developing, I sometimes leave the modal open when saving code (I use the live refresh), the modal remains open and there is no way to close, so I have to stop the program and restart it.

I am using version 6.0.0 of react-native-modal.

**Comment by mmazzarolo** [comment]
Unfortunately it's a known issue caused by the original modal.
We can't fix it until we migrate to a totally JS version of the modal (or until react-native fixes it).

**Comment by RWOverdijk** [comment]
Is there any news on this?

**Comment by pvinis** [comment]
@mmazzarolo what does RN have to fix? what is the "it"?

**Comment by mmazzarolo** [comment]
👋 Unless something changed, this issue happens with the `Modal` component from `react-native` (which is used by `react-native-modal`) and unless its fixed there we can't do much (except for re-writing `react-native-modal` from scratch in JS)

**Comment by RWOverdijk** [comment]
Gosh darnit... Thanks!

**Comment by pvinis** [comment]
Is there no way to send some final data to the app right before a reload? Or maybe when a reload happens, all modals should be closed? It feels like there must be a way to keep using the native modal **and** have what we want here.

**Comment by rewieer** [comment]
@pvinis I've been investigating this issue a few weeks ago. It appears that this is something related to the architecture of React-Native internals. See [this](https://github.com/facebook/react-native/issues/17986#issuecomment-443072147) for more information.
As of now this isn't something we can solve because we are depending on RN modal. Of course this will be fixed by itself whenever we migrate to a full-JS solution as the tear down will be done automatically.

**Comment by pvinis** [comment]
> And basically not worth the work to refactor the architecture only for this issue.
So how is that not worth it, but migrating to a js-only impl is worth it?

**Comment by rewieer** [comment]
Well I have no idea about the amount of effort required to fix this, I can't tell which one would be faster to implement. Quite frankly I'd have preferred this to be fixed on React-Native Core directly

**Comment by mmazzarolo** [comment]
> So how is that not worth it, but migrating to a js-only impl is worth it?
Migrating to JS would fix a lot of other issues as well, see the sticky #145 .

That said, if you have any idea on how to fix it we're open to PR and discussions.

**Comment by pvinis** [comment]
Of course. I will read about the other problems it might solve. I'm not against it, I just don't Ike skipping native just because there is a problem. But I have not invested so much time in that, and apparently, there are lots more problems than just one, like you said, which is fine. I look forward to an even better modal, js or not! Thanks for getting involved with this. :D

**Comment by Kalightortaio** [comment]
Does this only happen during development, or can this be reproduced somehow in production?

**Comment by pvinis** [comment]
I would say only in development since we cannot reload the app in production.

**Comment by louisch** [comment]
It can apparently happen in production if you're using codepush (and you're pushing code updates which reload the app in production)

**Comment by BAE86AEC1946B6AB60CCD7452DC811F0** [comment]
> It can apparently happen in production if you're [using codepush](https://github.com/facebook/react-native/issues/17986#issuecomment-386231347) (and you're pushing code updates which reload the app in production)

I also encountered this problem and used it with code-push. Is there a solution?
