### ISSUE TITLE
How could we add swipe down to close function?

### ISSUE THREAD

**Issue by tuandt** [react-native-community/react-native-modal#26]
Hi,

I love the way this module: https://github.com/maxs15/react-native-modalbox implemented swipe down to close. How could we add this function to our module? 

Thanks!

**Comment by mmazzarolo** [comment]
Hey!  
That's an interesting feature I already considered in the past.  
From my point of you it should be already possible implementing it by [applying the panhandlers on the view that you nest in the modal](http://moduscreate.com/animated_drag_and_drop_with_react_native/).  
The main drawback in this approach is that you won't be able to gradually fade the backdrop while dragging the modal (like in `react-native-modalbox`).  

I/We can also try handling the swipe directly from this modal and exposing some configuration props: It would need a re-work of `react-native-modal` internals, but if this feature is requested enough it would probably be worth a shot trying.

**Comment by tuandt** [comment]
Hi mmazzarolo,

Thank you for your great module. I think many people would like to have this feature.

Hope that some one can help.

**Comment by tanaytanay** [comment]
I would love to have this feature. Apart from that, everything is perfect.

**Comment by notehaha** [comment]
+1 for this feature. please

**Comment by joao-alberto** [comment]
Is someone working on this issue? I want to contribute

**Comment by mmazzarolo** [comment]
Hey @joao-alberto, as far as I know nobody is working on it, and currently I don't have time to actively develop this feature.  
If you're interested in tackling it I'll gladly help you though 👍

**Comment by theohdv** [comment]
As [react-native-modalbox](https://github.com/maxs15/react-native-modalbox/blob/master/index.js) seems to not be maintained anymore, I would like to add this feature to this component.

As this modal can enter the screen from top, bottom, right and left. I think we should add a prop to indicate in which direction we want the feature 'swipe to close' to be available (`swipeDirection` maybe?). I don't want to use the `animationOut` property because it is not always a string as the animation can be overridden.

For the implementation, I want to be inspired by `react-native-modalbox` project as it works really well but if you have any proposition!

This is my first contribution in this project so any idea or help is welcome.

**Comment by mmazzarolo** [comment]
@theohdv that would be great!  

I totally agree with the `swipeDirection` prop.   

> This is my first contribution in this project so any idea or help is welcome.  

Honestly I never tried to implement this feature so I won't be able to guide you on a PR, but I'll try to help you as much as possible: just post a comment in this thread if you have any question or if you need support :)

Thanks!

**Comment by theohdv** [comment]
I have few questions about the behaviour of the modal:
- If `animationOut` is set to "slideOutLeft" for example and `swipeDirection` is set to right. When the user swipes the modal to the right, does the modal need to be close using the `animationOut` prop (so in this case on the left) or it should disappear on the right of the screen?

- I added a `onSwipeClose` prop which is called when the `swipeTreshold` is reached (don't find another way to close it without adding this prop). If `onSwipeClose` is missing, what should I do when `swipeTreshold` is reached? Reposition the modal to the initial position? Do nothing and let the modal stuck at the release position?

I hope my english is understandable (do not hesitate to ask for more details),
Thanks!

**Comment by mmazzarolo** [comment]
> If `animationOut` is set to "slideOutLeft" for example and `swipeDirection` is set to right. When the user swipes the modal to the right, does the modal need to be close using the `animationOut` prop (so in this case on the left) or it should disappear on the right of the screen?  
 
In my opinion the `animationOut` prop could be completely ignored if the user is swiping the modal.  

> I added a `onSwipe` prop which is called when the `swipeTreshold` is reached (don't find another way to close it without adding this prop). If `onSwipe` is missing, what should I do when `swipeTreshold` is reached? Reposition the modal to the initial position? Do nothing and let the modal stuck at the release position?

In my honest opinion, since this is a controlled component, repositioning the modal on the initial position seems the best option to me. What do you think? 

Great questions, it seems you're right on track here 👍 

Also, no worries about your english, it's pretty good 🎉

**Comment by theohdv** [comment]
Yes I was also thinking that it was the best behaviour. Thanks for the details!

**Comment by mmazzarolo** [comment]
@theohdv no worries for the prettier part, I'll take a look at it by myself 👍 

@ Everyone else: @theohdv has release a PR #105 addressing the swipe functionality

**Comment by mmazzarolo** [comment]
Released on [v5.0.0-0 pre-release](https://github.com/react-native-community/react-native-modal/releases/tag/v5.0.0-0), thanks!
