### ISSUE TITLE
Is there a way to display Modal over the open Keyboard?

### ISSUE THREAD

**Issue by durdevic** [react-native-community/react-native-modal#285]
I am building sort of a messenger app and I am searching for a feature like on Telegram, when you click on a message, he opens a modal without dismissing a keyboard below the modal.

Help's users manage functions much quicker.

Cheers!

**Comment by rewieer** [comment]
Hello !
As far as I know it is not possible to keep the focus on an input while a modal is opened.

You can get around this by crafting your own view, putting it in position absolute and showing/hiding it whenever the user clicks the message, instead of using a modal. This is kind of what we're heading to with the full-js implementation of react-native-modal, but atm it's still a draft. There's still problems to solve.

React-native-modal cannot help you with it at the moment, sorry 😢

**Comment by littlehome-eugene** [comment]
Is this not the purpose of `avoidKeyboard` prop?
