### ISSUE TITLE
Modal does not show animations

### ISSUE THREAD

**Issue by yesIamFaded** [react-native-community/react-native-modal#287]
My Modal does not show animations when I try using: "animationIn" or "animationOut" but for some reason when I try animationType="slide" it does slide but its very slow and looks ugly because firstly the black opacity background slides in and then the modal just pops up after few seconds. 

I created a Stackoverflow Q for this before asking here but maybe you guys know the answer.

LINK: https://stackoverflow.com/questions/55648575/react-native-modal-doesnt-show-animations

**Comment by mmazzarolo** [comment]
I would suggest you to create a small repository with a minimal example to reproduce your issue.  
Most of the times by doing so you'll be able to detect where the issue is.  
Unfortunately without it (and without any info from the issue template) we won't be able to help... feel free to re-open an issue here if you discover any bug!
Good luck!
