### ISSUE TITLE
Setting swipe direction on modal cause 'bottom' style to behave haphazardly.

### ISSUE THREAD

**Issue by omeileo** [react-native-community/react-native-modal#315]
## Environment
System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 63.27 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.7.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 24, 26, 27, 28
        Build Tools: 23.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 

## Platforms
Android & iOS

## Versions
- react-native-modal: ^9.0.0
- react-native: 0.57.8
- react: 16.6.3

## Description
Setting `swipeDirection` while using the `bottom` style on the modal [set to 0] sees to the modal shifting up to near the middle of screen. Adjusting the bottom to a negative number sees to it being pushed further towards the bottom of the screen.

## Reproducible Demo
```
      // Modal
      <View style={styles.container}>
        <Modal
          animationIn={'slideInUp'}
          animationOut={'slideOutDown'}
          isVisible={isVisible}
          onBackdropPress={toggleReviewModal}
          onBackButtonPress={toggleReviewModal}
          onSwipeComplete={toggleReviewModal}
          style={styles.modal}
          swipeDirection={'down'}
        >
          <View style={styles.modalContainer}>
            <View style={styles.emojiContainer}>
              <Text style={styles.emoji}>😶</Text>
            </View>

            <View style={styles.ratingContainer}>
              <Text style={styles.modalTitle}>What Did You Think?</Text>
              
              <View style={styles.starsContainer}>
                { this.displayRatingStars() }
              </View>
            </View>
          </View>
        </Modal>

        { children }
      </View>
```

```
// Related Style
  container: {
    flex: 1
  },

  modal: {
    position: 'absolute',
    bottom: 0,
    margin: 0,
    width: '100%'
  },

  modalContainer: {
   backgroundColor: color.light,
   height: 145,
   alignItems: 'center',
   justifyContent: 'center',
   borderTopLeftRadius: 15,
   borderTopRightRadius: 15,
  },
```

**Comment by squalvj** [comment]
+1

**Comment by kenyontu** [comment]
I did some debugging and this happens because when you set `swipeDirection`, animated values for the `top` and `left` style properties are added to the same view that receives the style you pass to Modal.

**Final style:**

<img width="210" alt="Screen Shot 2019-07-20 at 15 34 19" src="https://user-images.githubusercontent.com/15267227/61575849-e2cf5180-ab03-11e9-90ec-d1fd762f1456.png">

**`top` and `left` values:**

<img width="265" alt="top and left values" src="https://user-images.githubusercontent.com/15267227/61575649-ead9c200-ab00-11e9-812b-86586825878f.png">

This means that you end up with a view that has `{top: 0, bottom: 0}`, causing the behaviour you described.

If you want to position the modal in the bottom of the screen, the Example App does this by passing the following style to `Modal`:
```js
{
  justifyContent: 'flex-end',
  margin: 0
}
```

You can check it in the Example App here:
https://github.com/react-native-community/react-native-modal/blob/master/example/App.js#L110
