### ISSUE TITLE
Swiping gesture isn't visible and modal wont hide before releasing the finger

### ISSUE THREAD

**Issue by mahdinba97** [react-native-community/react-native-modal#332]
## Info: 
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 834.24 MB / 11.90 GB
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: 4.9.4 - C:\watchman\watchman.EXE
  IDEs:
    Android Studio: Version  3.1.0.0 AI-173.4907809
    Visual Studio Code: Version 1.36

## Versions:
- Android: 9
- react-native-modal:11.1.0
- react-native:0.60
- react:16.8.6

## Description:
When I try to close the modal by swiping, it won't move but the backDrop starts to hide. and when the finger is released, the modal is closed. I mean the modal wouldn't move with my finger.

## Reproducible Demo
```
<Modal
  animationInTiming={700}
  animationOutTiming={700}
  useNativeDriver={true}
  hideModalContentWhileAnimating={true}
  swipeDirection="down"
  onSwipeComplete={this.toggleModal}
  isVisible={this.state.isModalVisible}
  onBackButtonPress={this.toggleModal}
  onBackdropPress={this.toggleModal}
  style={{
    backgroundColor: "white",
    marginTop: 300,
    marginBottom: 0,
    marginHorizontal: 0
  }}>
  <View
    style={{ flex: 1, padding: 30, justifyContent: "space-between" }}>
    <View>
      <Text
        style={{
          fontFamily: fonts.bold,
          textAlign: "center",
          color: "black",
          fontSize: 16
        }}>
        ایجاد سوال جدید
      </Text>
      <Divider />
    </View>

    <Input
      underlineColorAndroid="transparent"
      inputStyle={{ fontFamily: fonts.default }}
      containerStyle={{
        borderColor: "black",
        borderWidth: 1,
        borderRadius: 4
      }}
      multiline={true}
      numberOfLines={10}
      placeholder="متن سوال"
      textAlignVertical="top"
      shake={true}
    />
    <Button
      type="outline"
      style={{}}
      title="ثبت"
      containerStyle={{ borderColor: "black" }}
      titleStyle={{ fontFamily: fonts.bold, color: "black" }}
      onPress={this.toggleModal}
    />
  </View>
</Modal>

```

**Comment by julianoabrs** [comment]
Same thing happening here, in iOS as well

Using React Native 0.60.0 also

**Comment by mahdinba97** [comment]
Oh my god. It is a known issue and I didn't check it. sorry. #163

**Comment by kenyontu** [comment]
Hi @mahdinba97 I did some testing with your code and I think I found the cause of your issue.

The style passed to Modal is actually applied to a View responsible for positioning the child element of Modal. This means that in your example, what you see with a white background is this View instead of the "actual" modal.

Could you make the changes bellow and see if it solves your issue?
```js
// Remove style prop of Modal
<Modal
  isVisible={this.state.isModalVisible}
  swipeDirection="down"
  // other props...
  >
  // The children element of Modal receives the white background and { flex: 1 } is removed
  <View style={{ 
    padding: 30, 
    justifyContent: 'space-between'
    backgroundColor: 'white',
  }}>
    // Modal content...
  </View>
</Modal>
```

**Comment by kenyontu** [comment]
I did some digging and this is the expected behaviour when `useNativeDriver={true}`.

The PR #247 has the discussion on it. In addition, this part in the [docs](https://facebook.github.io/react-native/docs/animations#caveats) about Animations, mentions that `useNativeDriver` does not support position properties, which are required to make the modal move while the user is swiping.

**Comment by mahdinba97** [comment]
Thanks for the answer. And yes, I found that out just after I created this issue.
