### ISSUE TITLE
Why open modal with Tab Bar back to first item?

### ISSUE THREAD

**Issue by cotrim149** [react-native-community/react-native-modal#335]
## Ask your Question
In my project, I have a tab bar.
I put the modal in a component to open the camera in the second item of this tab bar.

When I click on my component, instants before the modal appears, some kind of "navigation" to the first item happens. It's a kind wird. It's like "re-render" of my tab bar before open modal.

What I can do to avoid this behavior?

I'm using: 
    "react-native-camera": "^2.11.1",
    "react-native-modal": "^11.1.0",
    "react-navigation": "^3.9.1",

**Comment by mmazzarolo** [comment]
Hi @cotrim149 !
I'm sorry but we can't help on this since it seems an integration problem with external libraries (and that we don't have enough info to reproduce). 
I would suggest you trying to replace `react-native-modal` with RN's own modal to see if the issue persists. If the issue seems to be `react-native-modal` specific fill a new issue with the details and we'll try to address it as soon as we can.
Thanks!
