### ISSUE TITLE
Navigation between screens with a button displayed in <Modal />

### ISSUE THREAD

**Issue by JVRodrigues256** [react-native-community/react-native-modal#51]
Hello everyone.

I'm displaying a button inside Modal, but when I click the button and navigate between the screens, the modal continues to be displayed.

I would like that when you click a button, <Modal /> is closed.
Is there any way to do this?

SCREEN I:
![error i](https://user-images.githubusercontent.com/28905128/28849639-5a10ec50-76ee-11e7-829c-7de7b57867a6.png)

SCREEN II:
![error ii](https://user-images.githubusercontent.com/28905128/28849659-714da386-76ee-11e7-8bfa-bb37acb17fa5.png)

**Comment by mmazzarolo** [comment]
Hi @JVRodrigues256, if I understood correctly what you're asking, this is more a "react pattern" issue then an issue related to react-native-modal.  

> I'm displaying a button inside Modal, but when I click the button and navigate between the screens, the modal continues to be displayed.  

Simply put, when the user click on your button you should first hide the modal, then start a navigation to your other screen.  
Something like this should work:  
```javascript
export default class YouFirstScreen extends Component {
  state = {
    isModalVisible: false
  }

  _showModal = () => this.setState({ isModalVisible: true })

  _hideModal = () => this.setState({ isModalVisible: false })

  _goToSecondScreen = () => {
    // First, hide the modal
    this._hideModal();
    // Then, navigate to your second screen
    yourNavigationApi.push('yourSecondScreen') 
  }

  render () {
    return (
      <View style={{ flex: 1 }}>
        <TouchableOpacity onPress={this._showModal}>
          <Text>Show the modal</Text>
        </TouchableOpacity>
        <Modal isVisible={this.state.isModalVisible}>
          <View style={{ flex: 1 }}>
            <TouchableOpacity onPress={this._goToSecondScreen}>
                <Text>Go to the second screen</Text>
             </TouchableOpacity>
          </View>
        </Modal>
      </View>
    )
  }

}
```

FYI the modal stays visible even when switching screens because you're (probably)  pushing the new screen in the navigation stack, which means that you're first screen will remain in memory (and, consequently, it won't destroy the modal).  

Please let me know if it solved your use issue.

**Comment by sabiya115** [comment]
@mmazzarolo i want to ask further one thing, your approach will take to second scree, but on coming back to previous screen, how do we get modal open , on back how we maintain the same screen as it was previous.
![image](https://user-images.githubusercontent.com/23252768/32210205-695b9878-be32-11e7-9217-83eb8251cb59.png)

**Comment by mmazzarolo** [comment]
You can't simply "leave the modal open", you must show it again (for example by setting the `isVisible` to true when your route gets focused)

**Comment by hoscarcito** [comment]
I undestand what you say @mmazzarolo , but doesn't the modal belong to the screen as a component from THAT screen?
I mean, I open a screen, then click on a button and a new screen is pushed. Why the modal is still in this new screen if it belongs to the first one?
Thanks in advance!

**Comment by wkoutre** [comment]
@hoscarcito 

It really depends on how you have your app's navigation set up.

Generally speaking, though, a Modal is a component being overlayed over the app. No matter what screen is on the top of the Nav stack, if the Modal's `isVisible` prop is true, it will be shown.

For example, in one of my apps I have a custom "Alert" component. It's a Modal, is always rendered under my Redux Provider, and has its own Redux reducer to make it visible, change what text is shows and what its buttons do, etc. But it's **not** a navigation screen.

React-navigation, react-native-router-flux, and other navigation implementations have a Modal Screen that is, indeed, a new route being pushed on the navigation stack. But if you're using this module or another based on React Native's primitive Modal, it's not going to be considered a separate navigation screen in your app unless you explicitly set it up that way.

**Comment by hoscarcito** [comment]
Ok. so the "problem" here is that the react-native modal is on top of the app, no matter which component/screens it belongs to. I thought it has something to do with components hierarchy.
I'll go with your solution but I guess a custom component with position absolute and visibility through a state would be better for this because I need this modal just for this screen.

Thanks for all your work!!

**Comment by mmazzarolo** [comment]
Thanks @wkoutre for taking the time for the perfect explanation.  

@hoscarcito you can still try implementing `react-native-modal` with your navigation router. I did it some times ago in `react-native-router-flux` and it worked perfectly: in my case I simply had to define a route and handle the modal behaviour using the navigation triggers (I can't be more specific right now, but if you're interested I can look for the project).

**Comment by hoscarcito** [comment]
@mmazzarolo OHHHH!! that would be great!!
I'm kinda lost with this because I have like a list of post and all of them dispatch a modal with its comments, and like facebook from there I can go to a different profile, but when I hit back, I don't know how to get the modal up with the same info. I thought to store the display status of the modal, but I think its too complicated because I have to turn it off when I got off the screen. Sorry for the bad explanation, I'm not too good at english 🙈

**Comment by jamessawyer** [comment]
Another modal library react-native-modalbox does a great job! react-native-modal will always overlay other navigation scenes!
